description = 'Simple osmdroid based map application'

apply plugin: 'com.android.application'
apply from: "$rootDir/gradle/android-signing.gradle"

group = project.property("pom.groupId")
version = project.property("pom.version")

android {
    namespace 'org.osmdroid.simplemap'
    compileSdk 37

    defaultConfig {
        applicationId 'org.osmdroid.osmdroid.simple.map'
        minSdkVersion 24
        multiDexEnabled = true
        targetSdkVersion 36
        versionName project.version
    }

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.8.0"
    implementation project(':osmdroid-android')
    implementation 'androidx.core:core-ktx:1.19.0'
}
