package org.osmdroid

// This file is automatically generated during the build.
// When making changes, only edit ./src/main/filtered/...
// https://github.com/osmdroid/osmdroid/issues/1500
class OsmdroidBuildInfo private constructor() {
    companion object {
        const val VERSION: String = "@pom.version@"
        const val BUILD_DATE: String = "@date@"
    }
}
