description = 'OpenMap in the Play Store, the example app for using osmdroid'

apply plugin: 'com.android.application'
apply from: "$rootDir/gradle/android-signing.gradle"


group = project.property("pom.groupId")
version = project.property("pom.version")

android {
    namespace 'org.osmdroid'
    compileSdk 37

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


        applicationId "org.osmdroid"

        minSdkVersion 24
        targetSdkVersion 36

   /*     compileSdkVersion(project.hasProperty('android.compileSdkVersion')
                ? Integer.parseInt(project.property('android.compileSdkVersion')) : 34)

        // default targetSdkVersion to API 23, if not provided
        targetSdkVersion(project.hasProperty('android.targetSdkVersion')
                ? Integer.parseInt(project.property('android.targetSdkVersion')) : 34)

        // default versionCode o 1 if not provided
        versionCode(project.hasProperty('android.versionCode')
                ? Integer.parseInt(project.property('android.versionCode')) : 34)

    */

        versionName project.version
    }
    lint {
        abortOnError false
    }

    testOptions {
        unitTests.all {
            // All the usual Gradle options.
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }

    packaging {
        resources {
            pickFirsts += ["androidsupportmultidexversion.txt", "META-INF/AL2.0", "META-INF/LGPL2.1"]
        }
    }


}


dependencies {
    //apparently google or gradle changed something so that
    //transitive dependencies of submodules in the same project
    //are not longer resolved...

    //osmdroid-mapsforge
    implementation 'org.mapsforge:mapsforge-map-android:0.25.0'
    implementation 'org.mapsforge:mapsforge-map:0.25.0'
    implementation 'org.mapsforge:mapsforge-themes:0.25.0'


    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation project(':osmdroid-android')
    implementation project(':osmdroid-geopackage')
    implementation project(':osmdroid-mapsforge')
    implementation project(':osmdroid-wms')
    implementation project(':osmdroid-shape')

    implementation 'io.github.missioncommand:mil-sym-android-renderer:0.2.5'

    //used for various demos for picking offline tile archives
    implementation 'com.github.angads25:filepicker:1.1.1'

    //used for bookmark demo
    implementation group: 'com.opencsv', name: 'opencsv', version: '5.12.0'

    //usual android stuff
    implementation "com.google.android.material:material:1.14.0" //needed for UI menuing
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.4.0"
    implementation "androidx.appcompat:appcompat:1.8.0"
    //crash logging
    implementation('ch.acra:acra:4.7.0') {
        exclude group: 'com.android.support', module: 'support-v4'
    }

    configurations.configureEach {
        exclude group: 'com.caverock', module: 'androidsvg-aar'
    }

    //memory leak testing
    implementation 'com.squareup.leakcanary:leakcanary-android:2.14'
    implementation 'androidx.core:core-ktx:1.19.0'

    //on device testing
    androidTestImplementation "androidx.annotation:annotation:1.10.0"


    androidTestImplementation "androidx.test:runner:1.7.0"
    androidTestImplementation "androidx.test:rules:1.7.0"
    // Optional -- UI testing with Espresso
    androidTestImplementation "androidx.test.espresso:espresso-core:3.7.0"
    // Optional -- UI testing with UI Automator
    androidTestImplementation "androidx.test.uiautomator:uiautomator:2.4.0"
}


// The instrumentation suite installs and grants permissions explicitly through adb.
