description = "A tool to package OpenStreetMap tiles"
apply plugin: 'java'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'distribution'
apply plugin: 'application'
apply plugin: 'maven-publish'

group = project.property("pom.groupId")
version =  project.property("pom.version")
application {
    mainClass = "org.osmdroid.mtp.OSMMapTilePackager"
}

test {
    testLogging {
        showStandardStreams = true
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(Javadoc) {
    failOnError false
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'org.apache.httpcomponents:httpmime:4.5.14'
    implementation 'org.apache.james:apache-mime4j:0.8.14'
    implementation 'org.xerial:sqlite-jdbc:3.53.2.1'


    testImplementation "org.junit.vintage:junit-vintage-engine:${project.property('junit.version')}"
}

//copy the instrumentation tests from the maven osmdroid-android-it src folder
task preBuildTask1(type: Copy) {
    println("copying StreamUtils Kotlin sources")
    description 'copy Kotlin classes from osmdroid-android.'
    from("${rootDir}/osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StreamUtils.kt")
    into "src/main/java/org/osmdroid/tileprovider/util/"

}

task preBuildTask2(type: Copy) {
    println("copying GEMF Kotlin sources")
    description 'copy Kotlin classes from osmdroid-android.'
    from("${rootDir}/osmdroid-android/src/main/java/org/osmdroid/util/GEMFFile.kt")
    into "src/main/java/org/osmdroid/util/"

}


task preBuildTask3(type: Copy) {
    println("copying api sources")
    description 'copy java classes from osmdroid-android.'
    from("${rootDir}/osmdroid-android/src/main/java/org/osmdroid/api/") {
        exclude 'IMyLocationOverlay.java'
        exclude 'Polyline.java'
        exclude 'Marker.java'
        exclude 'IProjection.java'
        exclude 'IMyLocationOverlay.kt'
        exclude 'Polyline.kt'
        exclude 'Marker.kt'
        exclude 'IProjection.kt'
    }
    into "src/main/java/org/osmdroid/api/"

}


task preBuildTask4(type: Delete) {
    println("removing android specific api sources")
    delete "${projectDir}/src/main/java/org/osmdroid/api/"
    delete "${projectDir}/src/main/java/org/osmdroid/api/IMyLocationOverlay.java"
    delete "${projectDir}/src/main/java/org/osmdroid/api/Polyline.java"
    delete "${projectDir}/src/main/java/org/osmdroid/api/Marker.java"
    delete "${projectDir}/src/main/java/org/osmdroid/api/IProjection.java"
    delete "${projectDir}/src/main/java/org/osmdroid/api/IMyLocationOverlay.kt"
    delete "${projectDir}/src/main/java/org/osmdroid/api/Polyline.kt"
    delete "${projectDir}/src/main/java/org/osmdroid/api/Marker.kt"
    delete "${projectDir}/src/main/java/org/osmdroid/api/IProjection.kt"
}

compileJava.dependsOn preBuildTask1
compileJava.dependsOn preBuildTask2
compileJava.dependsOn preBuildTask3
compileJava.dependsOn preBuildTask4

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = '17'
}

compileKotlin.dependsOn preBuildTask1
compileKotlin.dependsOn preBuildTask2
compileKotlin.dependsOn preBuildTask3
compileKotlin.dependsOn preBuildTask4

afterEvaluate {
    publishing {

        publications {
            release(MavenPublication) {
                from components.java
                groupId project.property("pom.groupId")
                artifactId project.name
                version = project.property("pom.version")
                pom {
                    description =  project.description
                    url = project.property("pom.url")

                    //scm, organization and developers are injected via other mechanisms

                    licenses {
                        license {
                            name=project.property("pom.licenses.license.0.name");
                            url=project.property("pom.licenses.license.0.url");
                            distribution=project.property("pom.licenses.license.0.distribution");
                        }

                    }
                }
            }

            pdZipPublication(MavenPublication) {
                artifact "build/distributions/OSMMapTilePackager-" + project.property("pom.version") + ".zip"

            }
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
